/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const HomeworkTriangleJudgeLazyImport = createFileRoute(
  '/homework/triangle-judge',
)()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeworkTriangleJudgeLazyRoute = HomeworkTriangleJudgeLazyImport.update({
  id: '/homework/triangle-judge',
  path: '/homework/triangle-judge',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/homework/triangle-judge.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/homework/triangle-judge': {
      id: '/homework/triangle-judge'
      path: '/homework/triangle-judge'
      fullPath: '/homework/triangle-judge'
      preLoaderRoute: typeof HomeworkTriangleJudgeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/homework/triangle-judge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/homework/triangle-judge'
  id: '__root__' | '/' | '/about' | '/homework/triangle-judge'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeworkTriangleJudgeLazyRoute: typeof HomeworkTriangleJudgeLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeworkTriangleJudgeLazyRoute: HomeworkTriangleJudgeLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/homework/triangle-judge"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/homework/triangle-judge": {
      "filePath": "homework/triangle-judge.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
