/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HomeworkTriangleJudgeRouteImport } from './routes/homework/triangle-judge/route'
import { Route as HomeworkCalendarProblemRouteImport } from './routes/homework/calendar-problem/route'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeworkTriangleJudgeRouteRoute = HomeworkTriangleJudgeRouteImport.update(
  {
    id: '/homework/triangle-judge',
    path: '/homework/triangle-judge',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/homework/triangle-judge/route.lazy').then((d) => d.Route),
)

const HomeworkCalendarProblemRouteRoute =
  HomeworkCalendarProblemRouteImport.update({
    id: '/homework/calendar-problem',
    path: '/homework/calendar-problem',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/homework/calendar-problem/route.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/homework/calendar-problem': {
      id: '/homework/calendar-problem'
      path: '/homework/calendar-problem'
      fullPath: '/homework/calendar-problem'
      preLoaderRoute: typeof HomeworkCalendarProblemRouteImport
      parentRoute: typeof rootRoute
    }
    '/homework/triangle-judge': {
      id: '/homework/triangle-judge'
      path: '/homework/triangle-judge'
      fullPath: '/homework/triangle-judge'
      preLoaderRoute: typeof HomeworkTriangleJudgeRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/homework/calendar-problem': typeof HomeworkCalendarProblemRouteRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/homework/calendar-problem': typeof HomeworkCalendarProblemRouteRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/homework/calendar-problem': typeof HomeworkCalendarProblemRouteRoute
  '/homework/triangle-judge': typeof HomeworkTriangleJudgeRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/homework/calendar-problem' | '/homework/triangle-judge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/homework/calendar-problem' | '/homework/triangle-judge'
  id:
    | '__root__'
    | '/'
    | '/homework/calendar-problem'
    | '/homework/triangle-judge'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeworkCalendarProblemRouteRoute: typeof HomeworkCalendarProblemRouteRoute
  HomeworkTriangleJudgeRouteRoute: typeof HomeworkTriangleJudgeRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeworkCalendarProblemRouteRoute: HomeworkCalendarProblemRouteRoute,
  HomeworkTriangleJudgeRouteRoute: HomeworkTriangleJudgeRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/homework/calendar-problem",
        "/homework/triangle-judge"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/homework/calendar-problem": {
      "filePath": "homework/calendar-problem/route.tsx"
    },
    "/homework/triangle-judge": {
      "filePath": "homework/triangle-judge/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
